### ISSUE TITLE
关于全局互信息计算的问题

### ISSUE THREAD

**Issue by FlyingRoastDuck** [bojone/infomax#2]
在[infomax_cifar10.py](https://github.com/bojone/infomax/blob/master/infomax_cifar10.py#L80)中您似乎是对同一图像global 特征之间进行concat而不是像论文中说的，对原始图像x和全局特征zx进行concat。能解释以下吗？另外，想知道您怎么理解文中公式（4）和图2对于全局互信息计算的。这里，T（x,E(x)）是原始图像和该图像对应的全局特征concat后进行判别吗？一个二维图像和一个一维向量concat中间是否有什么特殊处理？

**Comment by bojone** [comment]
首先，你应该去看看原论文的实现，他也是E(x)与E(x)进行concat的。
https://github.com/rdevon/DIM

其次，关于背后的原因，曾经在这里也讨论过：
https://kexue.fm/archives/6024#comment-9958

**Comment by FlyingRoastDuck** [comment]
谢谢。看起来您读过他的源码了，那我可以直接按照你的代码来复现吗？因为我不太熟悉他代码中提到的那个cortex框架

**Comment by bojone** [comment]
我不知道你有没有看
https://kexue.fm/archives/6024#comment-9958
处的讨论。我们这样做，其实是因为这样做是合理的，而不是仅仅因为“作者也是这样做的”。

至少在x与E(x) concat这一步上，你可以按照我目前的处理方法复现。

**Comment by FlyingRoastDuck** [comment]
好的，谢谢啦。
